version: '3'

services:
  web:
    build: .
    image: fanap_web
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8020:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    container_name: fanap_postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 1s
      retries: 3

  redis:
    image: redis:7-alpine

  celery_worker:
    build: .
    image: celery
    command: celery -A main.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    image: celery_beat
    command: celery -A main.celery beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  db_data: